Version =20
VersionRequired =20
Begin Form
    AutoCenter = NotDefault
    DividingLines = NotDefault
    AllowDesignChanges = NotDefault
    ViewsAllowed =1
    PictureAlignment =2
    DatasheetGridlinesBehavior =3
    GridY =10
    Width =30747
    DatasheetFontHeight =11
    ItemSuffix =55
    Right =20070
    Bottom =12240
    RecSrcDt = Begin
        0xee6c8e563cece540
    End
    RecordSource ="T_Artikel"
    Caption ="T_Artikel"
    DatasheetFontName ="Calibri"
    AllowDatasheetView =0
    FilterOnLoad =0
    ShowPageMargins =0
    DisplayOnSharePointSite =1
    DatasheetAlternateBackColor =15921906
    DatasheetGridlinesColor12 =0
    FitToScreen =1
    DatasheetBackThemeColorIndex =1
    BorderThemeColorIndex =3
    ThemeFontIndex =1
    ForeThemeColorIndex =0
    AlternateBackThemeColorIndex =1
    AlternateBackShade =95.0
    Begin
        Begin Label
            BackStyle =0
            FontSize =11
            FontName ="Calibri"
            ThemeFontIndex =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =0
            BorderTint =50.0
            ForeThemeColorIndex =0
            ForeTint =60.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin TextBox
            AddColon = NotDefault
            FELineBreak = NotDefault
            BorderLineStyle =0
            Width =1701
            LabelX =-1701
            FontSize =11
            FontName ="Calibri"
            AsianLineBreak =1
            BackThemeColorIndex =1
            BorderThemeColorIndex =1
            BorderShade =65.0
            ThemeFontIndex =1
            ForeThemeColorIndex =0
            ForeTint =75.0
            GridlineThemeColorIndex =1
            GridlineShade =65.0
        End
        Begin FormHeader
            Height =1026
            Name ="Formularkopf"
            AutoHeight =1
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =2
            BackTint =20.0
            Begin
                Begin Label
                    OverlapFlags =85
                    TextAlign =3
                    Left =342
                    Top =684
                    Width =456
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="NrArtikel_Bezeichnungsfeld"
                    Caption ="NrArtikel"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =342
                    LayoutCachedTop =684
                    LayoutCachedWidth =798
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =855
                    Top =684
                    Width =1881
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="Artikel_Bezeichnungsfeld"
                    Caption ="Artikel"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =855
                    LayoutCachedTop =684
                    LayoutCachedWidth =2736
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =3
                    Left =2793
                    Top =684
                    Width =399
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="NrFirma_Bezeichnungsfeld"
                    Caption ="NrFirma"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =2793
                    LayoutCachedTop =684
                    LayoutCachedWidth =3192
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =3249
                    Top =684
                    Width =1881
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="Hersteller_Bezeichnungsfeld"
                    Caption ="Hersteller"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =3249
                    LayoutCachedTop =684
                    LayoutCachedWidth =5130
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =5187
                    Top =684
                    Width =1881
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="Artikelname_Bezeichnungsfeld"
                    Caption ="Artikelname"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =5187
                    LayoutCachedTop =684
                    LayoutCachedWidth =7068
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =7125
                    Top =684
                    Width =969
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="ArtikelNr_Bezeichnungsfeld"
                    Caption ="ArtikelNr"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =7125
                    LayoutCachedTop =684
                    LayoutCachedWidth =8094
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =8151
                    Top =684
                    Width =969
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="ArtikelKategorie_Bezeichnungsfeld"
                    Caption ="ArtikelKategorie"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =8151
                    LayoutCachedTop =684
                    LayoutCachedWidth =9120
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =9177
                    Top =684
                    Width =1881
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="EANCOde_Bezeichnungsfeld"
                    Caption ="EANCOde"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =9177
                    LayoutCachedTop =684
                    LayoutCachedWidth =11058
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =11115
                    Top =684
                    Width =969
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="Liefereinheit_Bezeichnungsfeld"
                    Caption ="Liefereinheit"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =11115
                    LayoutCachedTop =684
                    LayoutCachedWidth =12084
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =12141
                    Top =684
                    Width =969
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="ArtikelRabatt_Bezeichnungsfeld"
                    Caption ="ArtikelRabatt"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =12141
                    LayoutCachedTop =684
                    LayoutCachedWidth =13110
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =13167
                    Top =684
                    Width =969
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="Einkaufspreis_Bezeichnungsfeld"
                    Caption ="Einkaufspreis"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =13167
                    LayoutCachedTop =684
                    LayoutCachedWidth =14136
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =14193
                    Top =684
                    Width =342
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="EKWährung_Bezeichnungsfeld"
                    Caption ="EKWährung"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =14193
                    LayoutCachedTop =684
                    LayoutCachedWidth =14535
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =14592
                    Top =684
                    Width =969
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="Einzelpreis_Bezeichnungsfeld"
                    Caption ="Einzelpreis"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =14592
                    LayoutCachedTop =684
                    LayoutCachedWidth =15561
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =15618
                    Top =684
                    Width =969
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="PreisFaktor_Bezeichnungsfeld"
                    Caption ="PreisFaktor"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =15618
                    LayoutCachedTop =684
                    LayoutCachedWidth =16587
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =16644
                    Top =684
                    Width =342
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="VKWährung_Bezeichnungsfeld"
                    Caption ="VKWährung"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =16644
                    LayoutCachedTop =684
                    LayoutCachedWidth =16986
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =17043
                    Top =684
                    Width =1881
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="BemArtikel_Bezeichnungsfeld"
                    Caption ="BemArtikel"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =17043
                    LayoutCachedTop =684
                    LayoutCachedWidth =18924
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =18981
                    Top =684
                    Width =969
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="LagerMindestMenge_Bezeichnungsfeld"
                    Caption ="LagerMindestMenge"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =18981
                    LayoutCachedTop =684
                    LayoutCachedWidth =19950
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =20007
                    Top =684
                    Width =969
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="Lagermenge_Bezeichnungsfeld"
                    Caption ="Lagermenge"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =20007
                    LayoutCachedTop =684
                    LayoutCachedWidth =20976
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =21033
                    Top =684
                    Width =969
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="LagerOrt_Bezeichnungsfeld"
                    Caption ="LagerOrt"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =21033
                    LayoutCachedTop =684
                    LayoutCachedWidth =22002
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =3
                    Left =22059
                    Top =684
                    Width =456
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="NrWarengruppe_Bezeichnungsfeld"
                    Caption ="NrWarengruppe"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =22059
                    LayoutCachedTop =684
                    LayoutCachedWidth =22515
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =3
                    Left =22572
                    Top =684
                    Width =456
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="ArtikelErfasst_Bezeichnungsfeld"
                    Caption ="ArtikelErfasst"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =22572
                    LayoutCachedTop =684
                    LayoutCachedWidth =23028
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =3
                    Left =23085
                    Top =684
                    Width =513
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="PrintMarkerArtikel_Bezeichnungsfeld"
                    Caption ="PrintMarkerArtikel"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =23085
                    LayoutCachedTop =684
                    LayoutCachedWidth =23598
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =3
                    Left =23655
                    Top =684
                    Width =456
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="LastUpdate_Bezeichnungsfeld"
                    Caption ="LastUpdate"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =23655
                    LayoutCachedTop =684
                    LayoutCachedWidth =24111
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =24168
                    Top =684
                    Width =969
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="WhoUpdate_Bezeichnungsfeld"
                    Caption ="WhoUpdate"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =24168
                    LayoutCachedTop =684
                    LayoutCachedWidth =25137
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =25194
                    Top =684
                    Width =1881
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="MarkerArtikel_Bezeichnungsfeld"
                    Caption ="MarkerArtikel"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =25194
                    LayoutCachedTop =684
                    LayoutCachedWidth =27075
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =1
                    Left =27132
                    Top =684
                    Width =1881
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="InfoArtikel_Bezeichnungsfeld"
                    Caption ="InfoArtikel"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =27132
                    LayoutCachedTop =684
                    LayoutCachedWidth =29013
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =85
                    TextAlign =3
                    Left =29070
                    Top =684
                    Width =1620
                    Height =315
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="NichtVerfügbar_Bezeichnungsfeld"
                    Caption ="NichtVerfügbar"
                    Tag ="DetachedLabel"
                    GridlineStyleBottom =1
                    GridlineColor =10921638
                    LayoutCachedLeft =29070
                    LayoutCachedTop =684
                    LayoutCachedWidth =30690
                    LayoutCachedHeight =999
                End
                Begin Label
                    OverlapFlags =215
                    Left =57
                    Top =57
                    Width =1854
                    Height =969
                    FontSize =20
                    BorderColor =8355711
                    ForeColor =6710886
                    Name ="Bezeichnungsfeld54"
                    Caption ="T_Artikel"
                    GridlineColor =10921638
                    LayoutCachedLeft =57
                    LayoutCachedTop =57
                    LayoutCachedWidth =1911
                    LayoutCachedHeight =1026
                End
            End
        End
        Begin Section
            Height =1254
            Name ="Detailbereich"
            AutoHeight =1
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
            Begin
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =342
                    Top =57
                    Width =456
                    Height =315
                    ColumnWidth =1701
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="NrArtikel"
                    ControlSource ="NrArtikel"
                    GridlineColor =10921638

                    LayoutCachedLeft =342
                    LayoutCachedTop =57
                    LayoutCachedWidth =798
                    LayoutCachedHeight =372
                End
                Begin TextBox
                    EnterKeyBehavior = NotDefault
                    ScrollBars =2
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =855
                    Top =57
                    Width =1881
                    Height =600
                    ColumnWidth =3000
                    TabIndex =1
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Artikel"
                    ControlSource ="Artikel"
                    GridlineColor =10921638

                    LayoutCachedLeft =855
                    LayoutCachedTop =57
                    LayoutCachedWidth =2736
                    LayoutCachedHeight =657
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =2793
                    Top =57
                    Width =399
                    Height =330
                    ColumnWidth =1530
                    TabIndex =2
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="NrFirma"
                    ControlSource ="NrFirma"
                    GridlineColor =10921638

                    LayoutCachedLeft =2793
                    LayoutCachedTop =57
                    LayoutCachedWidth =3192
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    EnterKeyBehavior = NotDefault
                    ScrollBars =2
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =3249
                    Top =57
                    Width =1881
                    Height =600
                    ColumnWidth =3000
                    TabIndex =3
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Hersteller"
                    ControlSource ="Hersteller"
                    GridlineColor =10921638

                    LayoutCachedLeft =3249
                    LayoutCachedTop =57
                    LayoutCachedWidth =5130
                    LayoutCachedHeight =657
                End
                Begin TextBox
                    EnterKeyBehavior = NotDefault
                    ScrollBars =2
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =5187
                    Top =57
                    Width =1881
                    Height =600
                    ColumnWidth =3000
                    TabIndex =4
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Artikelname"
                    ControlSource ="Artikelname"
                    GridlineColor =10921638

                    LayoutCachedLeft =5187
                    LayoutCachedTop =57
                    LayoutCachedWidth =7068
                    LayoutCachedHeight =657
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =7125
                    Top =57
                    Width =969
                    Height =330
                    ColumnWidth =3000
                    TabIndex =5
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="ArtikelNr"
                    ControlSource ="ArtikelNr"
                    GridlineColor =10921638

                    LayoutCachedLeft =7125
                    LayoutCachedTop =57
                    LayoutCachedWidth =8094
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =8151
                    Top =57
                    Width =969
                    Height =330
                    ColumnWidth =3000
                    TabIndex =6
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="ArtikelKategorie"
                    ControlSource ="ArtikelKategorie"
                    GridlineColor =10921638

                    LayoutCachedLeft =8151
                    LayoutCachedTop =57
                    LayoutCachedWidth =9120
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    EnterKeyBehavior = NotDefault
                    ScrollBars =2
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =9177
                    Top =57
                    Width =1881
                    Height =600
                    ColumnWidth =3000
                    TabIndex =7
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="EANCOde"
                    ControlSource ="EANCOde"
                    GridlineColor =10921638

                    LayoutCachedLeft =9177
                    LayoutCachedTop =57
                    LayoutCachedWidth =11058
                    LayoutCachedHeight =657
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =11115
                    Top =57
                    Width =969
                    Height =330
                    ColumnWidth =3000
                    TabIndex =8
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Liefereinheit"
                    ControlSource ="Liefereinheit"
                    GridlineColor =10921638

                    LayoutCachedLeft =11115
                    LayoutCachedTop =57
                    LayoutCachedWidth =12084
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =12141
                    Top =57
                    Width =969
                    Height =330
                    ColumnWidth =3000
                    TabIndex =9
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="ArtikelRabatt"
                    ControlSource ="ArtikelRabatt"
                    GridlineColor =10921638

                    LayoutCachedLeft =12141
                    LayoutCachedTop =57
                    LayoutCachedWidth =13110
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =13167
                    Top =57
                    Width =969
                    Height =330
                    ColumnWidth =3000
                    TabIndex =10
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Einkaufspreis"
                    ControlSource ="Einkaufspreis"
                    GridlineColor =10921638

                    LayoutCachedLeft =13167
                    LayoutCachedTop =57
                    LayoutCachedWidth =14136
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =14193
                    Top =57
                    Width =342
                    Height =330
                    ColumnWidth =960
                    TabIndex =11
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="EKWährung"
                    ControlSource ="EKWährung"
                    GridlineColor =10921638

                    LayoutCachedLeft =14193
                    LayoutCachedTop =57
                    LayoutCachedWidth =14535
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =14592
                    Top =57
                    Width =969
                    Height =330
                    ColumnWidth =3000
                    TabIndex =12
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Einzelpreis"
                    ControlSource ="Einzelpreis"
                    GridlineColor =10921638

                    LayoutCachedLeft =14592
                    LayoutCachedTop =57
                    LayoutCachedWidth =15561
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =15618
                    Top =57
                    Width =969
                    Height =330
                    ColumnWidth =3000
                    TabIndex =13
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="PreisFaktor"
                    ControlSource ="PreisFaktor"
                    GridlineColor =10921638

                    LayoutCachedLeft =15618
                    LayoutCachedTop =57
                    LayoutCachedWidth =16587
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =16644
                    Top =57
                    Width =342
                    Height =330
                    ColumnWidth =960
                    TabIndex =14
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="VKWährung"
                    ControlSource ="VKWährung"
                    GridlineColor =10921638

                    LayoutCachedLeft =16644
                    LayoutCachedTop =57
                    LayoutCachedWidth =16986
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    EnterKeyBehavior = NotDefault
                    ScrollBars =2
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =17043
                    Top =57
                    Width =1881
                    Height =1140
                    ColumnWidth =3000
                    TabIndex =15
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="BemArtikel"
                    ControlSource ="BemArtikel"
                    GridlineColor =10921638

                    LayoutCachedLeft =17043
                    LayoutCachedTop =57
                    LayoutCachedWidth =18924
                    LayoutCachedHeight =1197
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =18981
                    Top =57
                    Width =969
                    Height =330
                    ColumnWidth =3000
                    TabIndex =16
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="LagerMindestMenge"
                    ControlSource ="LagerMindestMenge"
                    GridlineColor =10921638

                    LayoutCachedLeft =18981
                    LayoutCachedTop =57
                    LayoutCachedWidth =19950
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =20007
                    Top =57
                    Width =969
                    Height =330
                    ColumnWidth =3000
                    TabIndex =17
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="Lagermenge"
                    ControlSource ="Lagermenge"
                    GridlineColor =10921638

                    LayoutCachedLeft =20007
                    LayoutCachedTop =57
                    LayoutCachedWidth =20976
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =21033
                    Top =57
                    Width =969
                    Height =330
                    ColumnWidth =3000
                    TabIndex =18
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="LagerOrt"
                    ControlSource ="LagerOrt"
                    GridlineColor =10921638

                    LayoutCachedLeft =21033
                    LayoutCachedTop =57
                    LayoutCachedWidth =22002
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =22059
                    Top =57
                    Width =456
                    Height =330
                    ColumnWidth =1530
                    TabIndex =19
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="NrWarengruppe"
                    ControlSource ="NrWarengruppe"
                    GridlineColor =10921638

                    LayoutCachedLeft =22059
                    LayoutCachedTop =57
                    LayoutCachedWidth =22515
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =22572
                    Top =57
                    Width =456
                    Height =330
                    ColumnWidth =1620
                    TabIndex =20
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="ArtikelErfasst"
                    ControlSource ="ArtikelErfasst"
                    GridlineColor =10921638

                    LayoutCachedLeft =22572
                    LayoutCachedTop =57
                    LayoutCachedWidth =23028
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =23085
                    Top =57
                    Width =513
                    Height =330
                    ColumnWidth =1200
                    TabIndex =21
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="PrintMarkerArtikel"
                    ControlSource ="PrintMarkerArtikel"
                    Format ="True/False"
                    GridlineColor =10921638

                    LayoutCachedLeft =23085
                    LayoutCachedTop =57
                    LayoutCachedWidth =23598
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =23655
                    Top =57
                    Width =456
                    Height =330
                    ColumnWidth =1620
                    TabIndex =22
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="LastUpdate"
                    ControlSource ="LastUpdate"
                    GridlineColor =10921638

                    LayoutCachedLeft =23655
                    LayoutCachedTop =57
                    LayoutCachedWidth =24111
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =24168
                    Top =57
                    Width =969
                    Height =330
                    ColumnWidth =3000
                    TabIndex =23
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="WhoUpdate"
                    ControlSource ="WhoUpdate"
                    GridlineColor =10921638

                    LayoutCachedLeft =24168
                    LayoutCachedTop =57
                    LayoutCachedWidth =25137
                    LayoutCachedHeight =387
                End
                Begin TextBox
                    EnterKeyBehavior = NotDefault
                    ScrollBars =2
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =25194
                    Top =57
                    Width =1881
                    Height =600
                    ColumnWidth =3000
                    TabIndex =24
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="MarkerArtikel"
                    ControlSource ="MarkerArtikel"
                    GridlineColor =10921638

                    LayoutCachedLeft =25194
                    LayoutCachedTop =57
                    LayoutCachedWidth =27075
                    LayoutCachedHeight =657
                End
                Begin TextBox
                    EnterKeyBehavior = NotDefault
                    ScrollBars =2
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =27132
                    Top =57
                    Width =1881
                    Height =1140
                    ColumnWidth =3000
                    TabIndex =25
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="InfoArtikel"
                    ControlSource ="InfoArtikel"
                    GridlineColor =10921638

                    LayoutCachedLeft =27132
                    LayoutCachedTop =57
                    LayoutCachedWidth =29013
                    LayoutCachedHeight =1197
                End
                Begin TextBox
                    OverlapFlags =85
                    IMESentenceMode =3
                    Left =29070
                    Top =57
                    Width =1620
                    Height =330
                    ColumnWidth =1620
                    TabIndex =26
                    BorderColor =10921638
                    ForeColor =4210752
                    Name ="NichtVerfügbar"
                    ControlSource ="NichtVerfügbar"
                    GridlineColor =10921638

                    LayoutCachedLeft =29070
                    LayoutCachedTop =57
                    LayoutCachedWidth =30690
                    LayoutCachedHeight =387
                End
            End
        End
        Begin FormFooter
            Height =0
            Name ="Formularfuß"
            AutoHeight =1
            AlternateBackThemeColorIndex =1
            AlternateBackShade =95.0
            BackThemeColorIndex =1
        End
    End
End
